# Docs general: https://docs.python.org/3.7/library/logging.html?highlight=logging#module-logging
# Docs for all handler types: https://docs.python.org/3/library/logging.handlers.html
version: 1

root:
  level: NOTSET
  handlers: [console_handler]

disable_existing_loggers: false

loggers:
  dev:
    level: DEBUG
    handlers: [file_handler]
    propagate: true # Inherit handlers

  prod:
    level: INFO
    handlers: [file_handler]
    propagate: false # Inherit handlers

handlers:
  console_handler:
    class: logging.StreamHandler
    level: NOTSET
    formatter: standard
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler # Make up to "backupCount"+1 log files of size "maxBytes"
    level: NOTSET
    formatter: standard
    filename: logs/standard.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"


